version: '3.5'

services:
  task_manager_postgres_db:
    container_name: task_manager_postgres_db
    image: postgres:14
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=${POSTGRES_DATABASE}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432
    networks:
      - task_manager
    restart: unless-stopped

  task_manager_pgadmin:
    container_name: task_manager_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ivan.reshetnikov.t@gmail.com
      PGADMIN_DEFAULT_PASSWORD: task_manager
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/d/GoIT/Git/task-manager/task-manager-backend/docker-volumes/pgadmin
    ports:
      - 127.0.0.1:5050:80
    networks:
      - task_manager
    restart: unless-stopped

  nestjs:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: task_manager_nest-app:latest
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - ACCESS_SECRET=${ACCESS_SECRET}
      - EXPIRE_TIME=${EXPIRE_TIME}
    ports:
      - '3000:3000'
    container_name: task_manager_nest-app
    depends_on:
      - task_manager_postgres_db
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - task_manager

networks:
  task_manager:
    driver: bridge

volumes:
  postgress:
  pgadmin:
